### ISSUE TITLE
is_photosphere checkbox not showing on photo edit page

### ISSUE THREAD

**Issue by Peter200lx** [mistic100/Piwigo-PhotoSphere#14]
Previously I would go to the photo edit page (`/admin.php?page=photo-####`) to mark photospheres so that the plugin would show the viewer for that photo. However I just tried that with the latest Piwigo version 13.7.0 which updated the design of the photo edit page and the checkbox no longer shows.

That being said for photos already marked the viewer shows properly. And I can work around the issue by using the batch manager to select photos and `Set Photo Sphere`

**Comment by mistic100** [comment]
I made a fix, will try to test it this evening and do a new release.

**Comment by mistic100** [comment]
0.2.4 released

perhaps you will have to purge compiled templates in Piwigo Maintenance page

**Comment by Peter200lx** [comment]
Yup, that fixed it, thank you!
