### ISSUE TITLE
Plugin cuts off the last few degrees of a 360

### ISSUE THREAD

**Issue by michaelh99** [mistic100/Piwigo-PhotoSphere#5]
Example at https://www.dragonseye.com/photos/picture.php?/19881-pano_20170317_164455/category/974-hot_springs_2017
The next photo in the album is the flat version.
This was generated with a Google Pixel in photosphere mode

**Comment by mistic100** [comment]
Your source image IS cut, you can see it by the bottom side which is not has deformed as the top side and also in the XMP tags :

```xml
         <GPano:CroppedAreaImageHeightPixels>4044</GPano:CroppedAreaImageHeightPixels>
         <GPano:CroppedAreaImageWidthPixels>9216</GPano:CroppedAreaImageWidthPixels>
         <GPano:FullPanoHeightPixels>4608</GPano:FullPanoHeightPixels>
         <GPano:FullPanoWidthPixels>9216</GPano:FullPanoWidthPixels>
         <GPano:CroppedAreaTopPixels>0</GPano:CroppedAreaTopPixels>
         <GPano:CroppedAreaLeftPixels>0</GPano:CroppedAreaLeftPixels>
```

See `CroppedAreaImageHeightPixels` (4044) which is lower than `FullPanoHeightPixels` (4608)

I don't know if it's the default behavior of the new camera to crop the bottom in order to hide the photographer, but there is nothing PhotoSphereViewer can do.

I can clear the XMP tags but you will get an ugly join point at the bottom.

**Comment by michaelh99** [comment]
The bottom is "cropped" because I didn't capture a full 360 vertically, only horizontally.  I didn't feel a need to get all the grass.

Is that what's causing the black band to appear where the join should be at either end?

**Comment by mistic100** [comment]
Perhaps we are not talking about the same thing, please upload a screenshot. And tell your browser.

**Comment by michaelh99** [comment]
Yeah, I think maybe you saw the hole at the bottom and thought that's what I was referring to.  Should have added a screenshot rather than thinking the problem was obvious.  I'm using 64bit FF 52.0.1 on Win 10

I do NOT see the problem in chrome

![pano-hole](https://cloud.githubusercontent.com/assets/2307675/24210163/3407d9de-0ef6-11e7-996c-c64d88c4c11b.jpg)

**Comment by michaelh99** [comment]
Also, 32b FF doesn't have this problem, 
Edge does.

**Comment by mistic100** [comment]
I just installed the latest 64bit Firefox, cannot reproduce the problem. Also I don't have Windows 10 so can't test further.

You can open an issue at https://github.com/mistic100/Photo-Sphere-Viewer but will be marked at "won't solve" until someone else can take a look.
