### ISSUE TITLE
"forward" sign does not work, "backwards" flash even not visible

### ISSUE THREAD

**Issue by nudelkiste** [mistic100/Piwigo-PhotoSphere#7]
Maybe it is easiest to explain my problem if you check out my page:
[https://sfinp.de/album/index.php?/category/von-oben](https://sfinp.de/album/index.php?/category/von-oben)

There are a couple of spheres.
Just click on a photo which is before one of the spheres and you'll recognize two flashes on the left and right side of the image to go forward and backward.
Click on the forward sign to see the sphere.
There will be the forward sign visible, but the backward sign is not.
Unfortunately the forwards-sign is even not clickable.

All this looks to me as an issue of z-index trouble, but maybe it is something completely different. I am not that experienced in CSS programming, that's why I ask for help here.

Just for Info: I use the plugin [VideoJS](https://github.com/xbgmsharp/piwigo-videojs/) which causes me a similar problem.
The backward flash is missing while the forward flash is visible. But in the Video, the forward flash remains functional.
example:
[https://sfinp.de/album/picture.php?/87/category/von-oben](https://sfinp.de/album/picture.php?/87/category/von-oben
)

looking forward to fix this little issue, as I love the tool - thanks a lot for sharing it.

**Comment by mistic100** [comment]
This is a problem with Stripped theme itself : if you reduce the width of your browser you will see the "backward" button always goes under the photo, even for standard ones.

![screenshot_2019-03-03 2019-01-20 seenplatte wortwortlich schone fotos in perl sans frontiere - inventaire des photos](https://user-images.githubusercontent.com/41597/53701476-2d268f00-3dfe-11e9-9e10-ee4755a8acf0.png)

**Comment by nudelkiste** [comment]
Well, this explains why the backward button disappears, but does it explain why the forward-button is dysfunctional while showing spheres?

**Comment by mistic100** [comment]
Yes, same issue, adding "z-index: 100" to both buttons solves everything.

**Comment by nudelkiste** [comment]
did it - many thanks for hinting me to the right topic

themes/stripped# vi theme.css
#imgnext, #imgprev {
        position: absolute;
        height:150px;
        width:20px;
        top:50%;
        margin-top:-75px;
        **z-index: 100;**
}

**Comment by mistic100** [comment]
Please notify the theme author (on Piwigo forum) in order to fix it for everyone.

---

And be aware that you modified a file which is subject to be overwritten by automatic updates.

**Comment by nudelkiste** [comment]
Was not able to figure out how to contact them directly. 
So I posted the issue in the Forum:
https://piwigo.org/forum/viewtopic.php?pid=172747#p172747
